export const buttons = [
  {
    id: 1,
    name: "7",
    type: "number",
    value: "7",
    className: "number",
  },
  {
    id: 2,
    name: "8",
    type: "number",
    value: "8",
    className: "number",
  },
  {
    id: 3,
    name: "9",
    type: "number",
    value: "9",
    className: "number",
  },
  {
    id: 4,
    name: "DEL",
    type: "operator",
    value: null,
    className: "del-button",
  },
  {
    id: 5,
    name: "4",
    type: "number",
    value: "4",
    className: "number",
  },
  {
    id: 6,
    name: "5",
    type: "number",
    value: "5",
    className: "number",
  },
  {
    id: 7,
    name: "6",
    type: "number",
    value: "6",
    className: "number",
  },
  {
    id: 8,
    name: "+",
    type: "operator",
    value: "+",
    className: "number",
  },
  {
    id: 9,
    name: "1",
    type: "number",
    value: "1",
    className: "number",
  },
  {
    id: 10,
    name: "2",
    type: "number",
    value: "2",
    className: "number",
  },
  {
    id: 11,
    name: "3",
    type: "number",
    value: "3",
    className: "number",
  },
  {
    id: 12,
    name: "-",
    type: "operator",
    value: "-",
    className: "number",
  },
  {
    id: 13,
    name: ".",
    type: "operator",
    value: null,
    className: "number",
  },
  {
    id: 14,
    name: "0",
    type: "number",
    value: 0,
    className: "number",
  },
  {
    id: 15,
    name: "/",
    type: "operator",
    value: "/",
    className: "number",
  },
  {
    id: 16,
    name: "x",
    type: "operator",
    value: "*",
    className: "number",
  },
  {
    id: 17,
    name: "RESET",
    type: "operator",
    value: null,
    className: "reset-button",
  },
  {
    id: 18,
    name: "=",
    type: "operator",
    value: null,
    className: "equals-button",
  },
];
